export const expCategories = [
  { icon: '🌽', name: 'Grocery' },
  { icon: '☕', name: 'Coffee' },
  { icon: '🍜', name: 'Meal' },
  { icon: '💰', name: 'Interest' },
  { icon: '📽️', name: 'Entertainments' },
  { icon: '💡', name: 'Utility bills' },
  { icon: '🛖️', name: 'Rent' },
  { icon: '✈️', name: 'Traveling' },
  { icon: '🛒', name: 'Household supplies' },
  { icon: '🛹', name: 'Exercise' },
  { icon: '📱', name: 'Phone bill' },
  { icon: '🚗', name: 'Vehicle' },
  { icon: '💄', name: 'Beauty' },
  { icon: '🚌', name: 'Transportation' },
  { icon: '💊', name: 'Medical' },
  { icon: '📤', name: 'Carry-over' },
  { icon: '💵', name: 'Savings' },
  { icon: '👖', name: 'Clothing' },
  { icon: '🎓', name: 'Education' },
  { icon: '📚', name: 'Books' },
  { icon: '🟠', name: 'Others' },
];

export const incCategories = [
  { icon: '💸', name: 'Salary' },
  { icon: '🪙', name: 'Asset Withdraw' },
  { icon: '💰', name: 'Interest' },
  { icon: '💵', name: 'Allowance' },
  { icon: '📥', name: 'Carry-over' },
  { icon: '🟢', name: 'Others' },
];
